// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mongoconnector "github.com/skyaxl/synack/pkg/mongoconnector"
	mock "github.com/stretchr/testify/mock"
)

// MongoConnector is an autogenerated mock type for the MongoConnector type
type MongoConnector struct {
	mock.Mock
}

// Connect provides a mock function with given fields: ctx
func (_m *MongoConnector) Connect(ctx context.Context) (mongoconnector.MongoCollection, error) {
	ret := _m.Called(ctx)

	var r0 mongoconnector.MongoCollection
	if rf, ok := ret.Get(0).(func(context.Context) mongoconnector.MongoCollection); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mongoconnector.MongoCollection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
